create table if not exists person
(
    id          int primary key generated by default as identity,
    name        varchar(100) not null,
    password    varchar(100) not null,
    email       varchar(50)  not null,
    role        varchar(20)  not null,
    status_role varchar(20)  not null
);

create table  if not exists request
(
    id          int primary key generated by default as identity,
    header      varchar(50)   not null,
    description varchar(5000) not null,
    person_id   int           references person (id) on delete set null,
    status      varchar(20)   not null,
    created_at  timestamp default now()
);

insert into person(name, password, email, role, status_role)
values (
        'admin','$2a$12$QyumFAO8XjRVPLoI0Z.piuoKbRH1f/7b37AcDgaXATuPKn2S5.zWe',
        'admin@admin','ADMIN','ACTIVE'
        );
insert into person(name, password, email, role, status_role)
values (
           'user1','$2a$12$lJrrNI//hbFoTgvSe3rxn.zAO6.mPpjvg/VcYjKmeRyrfEMugZYd.',
           'user1@user','USER','ACTIVE'
       );
insert into person(name, password, email, role, status_role)
values (
           'user2','$2a$12$LrywdxDI.3Ttd44piA1qcOD13tIS9tWrgkCh26ywgUw6nPx1JOxr.',
           'user2@user','USER','ACTIVE'
       );
insert into person(name, password, email, role, status_role)
values (
           'operator','$2a$12$FdHPv7XGPJWVG20Dziuun.kk4V9PT2b2MyA8mm3JHNvUgV/vj9.xy',
           'operator@operator','OPERATOR','ACTIVE'
       );